# Report Configuration
version: "1.0"

# Reference ranges for dysbiosis calculation
reference_ranges:
  Actinomycetota: [0.1, 8.0]
  Bacillota: [20.0, 70.0]
  Bacteroidota: [4.0, 40.0]
  Pseudomonadota: [2.0, 35.0]
  Fibrobacterota: [0.1, 5.0]

# Dysbiosis index thresholds
dysbiosis_thresholds:
  normal: 20
  mild: 50

# Color scheme
colors:
  primary_blue: "#1E3A8A"
  green: "#10B981"
  teal: "#14B8A6"
  header_bg: "#F8FAFC"
  text_dark: "#1F2937"
  text_light: "#6B7280"

# Asset paths
assets_path: "assets"

# Template settings
templates:
  default: "report_full.j2"
  languages:
    - en
    - pl
    - jp

# Laboratory information
laboratory:
  name: "HippoVet Laboratory"
  accreditation: "ISO 15189"
  contact:
    phone: "+48 123 456 789"
    email: "lab@hippovet.com"
    website: "www.hippovet.com"

# LLM settings (Week 2)
llm:
  enabled: false
  provider: "openai"
  model: "gpt-3.5-turbo"

# Species filtering
species_filtering:
  # List of eukaryotic species to exclude from bacterial analysis
  exclude_eukaryotes:
    - "Homo sapiens"
    - "Papaver somniferum"
    - "Humulus lupulus"
    - "Micromonospora siamensis"
    - "Phocaeicola vulgatus"
  # Also exclude anything from these kingdoms
  exclude_kingdoms:
    - "Eukaryota"
    - "Viridiplantae"
    - "Metazoa"
    - "Fungi"

# Kraken2 Configuration
kraken2:
  enabled: true
  default_database: "standard"
  databases:
    standard: "/home/trentleslie/kraken2_databases/standard"
    silva: "/home/trentleslie/kraken2_databases/silva"
    custom_equine: "/home/trentleslie/kraken2_databases/custom_equine"

  parameters:
    threads: 32
    confidence_threshold: 0.1
    minimum_hit_groups: 2
    memory_mapping: false
    quick_mode: false

  bracken:
    enabled: false
    read_length: 150
    classification_level: "S"

  fallback:
    use_biopython: true
    min_classified_threshold: 0.05  # Fall back if <5% reads classified